import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation } from "../navigation";
import { ModeToggle } from "@/components/ui/mode-toggle";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <header className="flex flex-row justify-between bg-teal-300 items-center w-screen">
        <Link className="flex hover:text-blue-600" href="/">
          Davis Community Meals and Housing
        </Link>
        <span className="flex">
          <span>
            <Navigation />
          </span>
          <span>
            <ModeToggle />
          </span>
        </span>
      </header>
      {children}
    </div>
  );
}
