import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "./navigation";

import { AuthProvider } from "@propelauth/nextjs/client";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/ui/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL!}>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="flex flex-row justify-between bg-teal-300 items-center w-screen">
              <span className="flex">Davis Community Meals and Housing</span>
              <span className="flex">
                <Navigation />
              </span>
              <span className="flex">
                <ModeToggle />
              </span>
            </header>
            {children}
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
