import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "./header";

import { AuthProvider } from "@propelauth/nextjs/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL!}>
        <body className={inter.className}>
          <header className="flex space-between">
            <span>Davis Community Meals and Housing</span>
            <NavigationMenuDemo />
          </header>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
